[[pages]]
path = "/"
screenshotTimestamp = "2026-05-01T20:59:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8bf248cf-779e-474a-85eb-0d6c3e9c0042/82eedd91-3d0b-4e84-a179-8e34ae725ddf/dpulcho"

[[pages]]
path = "/services"
screenshotTimestamp = "2026-05-01T19:23:04Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8bf248cf-779e-474a-85eb-0d6c3e9c0042/82eedd91-3d0b-4e84-a179-8e34ae725ddf/m1XfJgG"

[[pages]]
path = "/policies/complaints"
screenshotTimestamp = "2026-05-01T17:09:39Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8bf248cf-779e-474a-85eb-0d6c3e9c0042/82eedd91-3d0b-4e84-a179-8e34ae725ddf/YtyE5uw"

[[pages]]
path = "/#about"
screenshotTimestamp = "2026-05-01T17:12:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8bf248cf-779e-474a-85eb-0d6c3e9c0042/82eedd91-3d0b-4e84-a179-8e34ae725ddf/38oyd7Z"
